# Generated by Django 4.1.1 on 2022-09-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0002_alter_transaction_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="createdAt",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
